services:
  user_service_nodejs:
    build:
      context: ./user_service/nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  user_service_python:
    build:
      context: ./user_service/python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  post_service_nodejs:
    build:
      context: ./post_service/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  post_service_python:
    build:
      context: ./post_service/python
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  notification_service_nodejs:
    build:
      context: ./notification_service/nodejs
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  notification_service_python:
    build:
      context: ./notification_service/python
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  comment_service_nodejs:
    build:
      context: ./comment_service/nodejs
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  comment_service_python:
    build:
      context: ./comment_service/python
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
