services:
  postgres:
    image: postgres:13
    container_name: socialmediaplatformdesign-postgres-1
    environment:
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    container_name: socialmediaplatformdesign-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user_service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  post_service:
    build:
      context: ./services/post_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  notification_service:
    build:
      context: ./services/notification_service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  comment_service:
    build:
      context: ./services/comment_service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: social_media_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MONGO_HOST: mongo
      MONGO_PORT: 27017

volumes:
  postgres_data:
  mongo_data:

networks:
  default:
    name: socialmediaplatformdesign_default
