# Elasticsearch configuration file

cluster.name: "elasticsearch"
node.name: "node-1"
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 0.0.0.0
http.port: 9200

# Cluster Settings
discovery.type: single-node
