version: '3.8'

services:
  user_service_nodejs:
    build:
      context: ../../../user_service/nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  user_service_python:
    build:
      context: ../../../user_service/python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  post_service_nodejs:
    build:
      context: ../../../post_service/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  post_service_python:
    build:
      context: ../../../post_service/python
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  postgres_data:
  mongo_data:
